# Generated by Django 5.0.3 on 2024-03-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("dead_line", models.DateField()),
                ("finished_at", models.DateField(null=True)),
            ],
        ),
    ]
